/* ── Customer portal HTML server-render endpoint ─────────────────────────
   Replaces the previous direct-static-file rewrite for /booking/<token>.
   Vercel previously rewrote that path straight to booking-portal.html;
   now the rewrite targets this function (see vercel.json) so we can
   inject vessel-specific Open Graph metadata before the HTML reaches a
   social-preview crawler.

   Why: social platforms (Facebook, iMessage, Twitter, etc.) fetch HTML
   and parse <meta property="og:*"> tags. They do NOT execute JavaScript.
   Setting og:image client-side would never reach a crawler. So the
   image-by-vessel decision has to happen server-side, before HTML hits
   the wire.

   Flow:
     1. Vercel rewrites /booking/<token> to /api/portal-html?token=<token>
     2. This handler reads the token, looks up the booking via the existing
        findBookingByPortalToken helper from lib/storage.js
     3. Substitutes two placeholders in the HTML:
          __OG_IMAGE_URL__   → vessel hero (yacht or pontoon) on cdn URL
          __PORTAL_TOKEN__   → the exact token for og:url
     4. Returns the modified HTML with Cache-Control: no-store

   Cache-Control is critical: different tokens produce different og:images.
   Edge caching based on path alone would serve the wrong image to a
   different customer.

   Module-level HTML caching: the static booking-portal.html doesn't change
   between requests, so reading it once at module init (function cold start)
   and reusing across warm invocations cuts response time. Falls back to
   per-request read if init-time read failed for any reason. */

const fs = require('fs');
const path = require('path');
const { findBookingByPortalToken } = require('../lib/storage');

const SITE_BASE = 'https://www.texasforevercharters.com';

/* Vessel → OG image map. Absolute URLs (relative paths don't resolve for
   off-site crawlers). Uses purpose-built thumbnail variants sized for
   social-preview surfaces (~856×532, ~150-200KB) — separate from the
   full-res marketing-page heroes at /images/yacht-main-photo.JPG and
   /images/bentley-main-photo.jpeg, which would over-fetch a 4.7MB image
   for a preview frame. Default falls back to yacht (the more iconic
   vessel) for missing/unknown vessel values. */
const VESSEL_OG_IMAGES = {
  yacht:   SITE_BASE + '/images/yacht-thumbnail.jpg',
  pontoon: SITE_BASE + '/images/pontoon-thumbnail.jpg',
};
const DEFAULT_OG_IMAGE = VESSEL_OG_IMAGES.yacht;

/* Cache the HTML at module load. Vercel functions reuse module state
   across warm invocations on the same instance, so this read happens once
   per cold start rather than once per request. Read failure here is
   non-fatal — the handler falls back to a per-request read. */
let cachedHtml = null;
let cachedHtmlReadError = null;
try {
  cachedHtml = fs.readFileSync(path.join(__dirname, '..', 'booking-portal.html'), 'utf8');
} catch (err) {
  cachedHtmlReadError = err;
  console.error('[portal-html] module-init HTML read failed:', err.message);
}

/* 32-char hex token validator. Matches the shape generated by
   lib/storage.js:generatePortalToken (16 bytes → 32 hex chars). Mirrors
   api/portal.js:71 which does the same validation. Invalid-shape tokens
   skip the booking lookup but still serve the HTML — the page's own
   client-side error UI will surface the bad-token state to the user. */
const TOKEN_RE = /^[a-f0-9]{32}$/i;

module.exports = async function handler(req, res) {
  /* Load HTML — prefer the module-cached copy, fall back to per-request
     read if module init failed. If both fail, return 500 with a clear
     message so deployment problems surface in logs. */
  let html = cachedHtml;
  if (!html) {
    try {
      html = fs.readFileSync(path.join(__dirname, '..', 'booking-portal.html'), 'utf8');
    } catch (err) {
      console.error('[portal-html] request-time HTML read failed:', err.message,
        '| module-init error was:', cachedHtmlReadError && cachedHtmlReadError.message);
      return res.status(500).send('Portal page unavailable — please try again or call (737) 368-1669.');
    }
  }

  /* Parse token from query (Vercel passes the rewrite's :token path param
     as ?token=<value>). Lowercase + trim defensively. */
  const rawToken = (req.query && req.query.token) ? String(req.query.token).trim().toLowerCase() : '';
  const tokenValid = TOKEN_RE.test(rawToken);

  /* Look up vessel. Failures here (token invalid, booking missing, Supabase
     blip) all fall through to the default og:image — the page's own
     client-side error UI handles the "booking not found" case downstream
     for the actual customer view; we just need to produce a valid HTML
     response with sensible defaults for crawlers. */
  let ogImage = DEFAULT_OG_IMAGE;
  if (tokenValid) {
    try {
      const booking = await findBookingByPortalToken(rawToken);
      if (booking && VESSEL_OG_IMAGES[booking.vessel]) {
        ogImage = VESSEL_OG_IMAGES[booking.vessel];
      }
    } catch (err) {
      console.error('[portal-html] booking lookup failed for og:image — defaulting:', err.message);
    }
  }

  /* Substitute placeholders. Token placeholder uses the raw (validated)
     value so og:url correctly mirrors what the customer sees in their
     address bar. If token is invalid, the og:url renders with an empty
     token segment — broken-looking on a crawler, but invalid-token URLs
     don't legitimately get shared so this is acceptable. */
  const portalTokenForUrl = tokenValid ? rawToken : '';
  const rendered = html
    .replace(/__OG_IMAGE_URL__/g, ogImage)
    .replace(/__PORTAL_TOKEN__/g, portalTokenForUrl);

  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store');
  res.status(200).send(rendered);
};
